# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_donaton', models.IntegerField(default=0)),
                ('don_date', models.DateTimeField(verbose_name='donation date')),
                ('trans_date', models.DateTimeField(verbose_name='transaction date')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_donor', models.IntegerField(default=0)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('about_yourself', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('available', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField(default=0)),
                ('blood_group', models.CharField(max_length=200)),
                ('last_donated', models.DateTimeField(verbose_name='last donated')),
                ('trans_date', models.DateTimeField(verbose_name='transaction date')),
            ],
        ),
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_requester', models.IntegerField(default=0)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField(default=0)),
                ('blood_group', models.CharField(max_length=200)),
                ('units', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('trans_date', models.DateTimeField(verbose_name='transaction date')),
            ],
        ),
        migrations.AddField(
            model_name='donations',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation_add.Donor'),
        ),
        migrations.AddField(
            model_name='donations',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation_add.Requester'),
        ),
    ]
