# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 18:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donation_add', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RequestTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_requestid', models.IntegerField(default=0)),
                ('requestFor', models.CharField(max_length=200)),
                ('requestContactName', models.CharField(max_length=200)),
                ('requestContactNumber', models.IntegerField(default=0)),
                ('requestNoOfUnits', models.IntegerField(default=0)),
                ('requestLocation', models.CharField(max_length=200)),
                ('requestGender', models.CharField(max_length=200)),
                ('requstStatus', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_userid', models.IntegerField(default=0)),
                ('full_name', models.CharField(max_length=200)),
                ('contact_number', models.IntegerField(default=0)),
                ('entity', models.CharField(max_length=200)),
                ('userType', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('user_available', models.CharField(max_length=200)),
                ('blood_group', models.CharField(max_length=200)),
                ('userPreference', models.CharField(max_length=200)),
                ('trans_date', models.DateTimeField(verbose_name='transaction date')),
            ],
        ),
        migrations.RenameField(
            model_name='donations',
            old_name='don_date',
            new_name='donationDate',
        ),
        migrations.RemoveField(
            model_name='donations',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='donations',
            name='id_donaton',
        ),
        migrations.RemoveField(
            model_name='donations',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='donations',
            name='trans_date',
        ),
        migrations.AddField(
            model_name='donations',
            name='donationAtFord',
            field=models.CharField(default='N', max_length=200),
        ),
        migrations.AddField(
            model_name='donations',
            name='donationLocation',
            field=models.CharField(default=datetime.datetime(2016, 9, 7, 18, 18, 58, 992697, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requesttable',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation_add.User'),
        ),
        migrations.AddField(
            model_name='donorslist',
            name='requestid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation_add.RequestTable'),
        ),
        migrations.AddField(
            model_name='donorslist',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation_add.User'),
        ),
        migrations.AddField(
            model_name='donations',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='donation_add.User'),
            preserve_default=False,
        ),
    ]
