# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-08 23:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donation_add', '0002_auto_20160907_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requesttable',
            old_name='requstStatus',
            new_name='requestStatus',
        ),
        migrations.RemoveField(
            model_name='donations',
            name='donationAtFord',
        ),
        migrations.RemoveField(
            model_name='requesttable',
            name='userid',
        ),
        migrations.AddField(
            model_name='donations',
            name='requestGender',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donations',
            name='requestLocation',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donations',
            name='requstStatus',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requesttable',
            name='trans_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 8, 23, 37, 29, 539003, tzinfo=utc), verbose_name='transaction date'),
            preserve_default=False,
        ),
    ]
