# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-08 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation_add', '0003_auto_20160908_2337'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserDetails',
        ),
    ]
