# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-11 08:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donation_add', '0005_donations_id_donationid'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='trans_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 11, 8, 23, 48, 513512, tzinfo=utc), verbose_name='transaction date'),
            preserve_default=False,
        ),
    ]
