# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-11 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_add', '0007_donationdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationdetails',
            name='id',
        ),
        migrations.RemoveField(
            model_name='donationdetails',
            name='id_donationid',
        ),
        migrations.AddField(
            model_name='donationdetails',
            name='donationid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
