# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-11 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_add', '0011_auto_20160911_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donations',
            name='donationid',
        ),
        migrations.AddField(
            model_name='donations',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donations',
            name='id_donationid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donations',
            name='test',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
