# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-11 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation_add', '0015_auto_20160911_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='requestid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='donation_add.RequestTable'),
            preserve_default=False,
        ),
    ]
